no-permission: "&cInsufficient Permissions."
unmuted-chat-message: "&aunmuted the chat."
muted-chat-message: "&amuted the chat."
frozen-message: "&aYou have been frozen! &8&o(Please join our discord, discord.gg/)"
unfrozen-message: "&aYou have been unfrozen!"
help:
  - "&8-------------------------------"
  - "&cCheerios&fStaff"
  - ""
  - "&c[] &fOptional Arguments"
  - "&c<> &fRequired Arguments"
  - "&8-------------------------------"
  - "&4&lGENERAL COMMANDS"
  - "&cmutechat: &fUse this command to mute chat! &8&o(cheeriosstaff.mutechat)"
  - "&cstaffchat [message]: &fUse this command to use staff chat! &8&o(cheeriosstaff.staffchat)"
  - "&cstaffmode [player]: &fUse this command to enter staff mode! &8&o(cheeriosstaff.staff)"
  - "&cfreeze <player>: &fUse this command to freeze a player! &8&o(cheeriosstaff.freeze)"
  - "&8-------------------------------"